version: '3.4'

services:
  api:
    image: piratetiger/my-nas-api
    networks:
      - mynas-network

  ui:
    image: piratetiger/my-nas-ui
    networks:
      - mynas-network

  site:
    image: piratetiger/my-nas-site
    depends_on:
      - api
      - ui
    networks:
      - mynas-network

networks:
  mynas-network:
    driver: bridge
