FROM mcr.microsoft.com/dotnet/core/aspnet:2.2
RUN apt-get update \
    && apt-get install -y --allow-unauthenticated \
        libc6-dev \
        libgdiplus \
        libx11-dev \
     && rm -rf /var/lib/apt/lists/*
COPY backend/MyNAS.Site/bin/Release/netcoreapp2.2/publish ./
COPY frontend/dist/UI ./wwwroot
ENTRYPOINT ["dotnet", "MyNAS.Site.dll"]
EXPOSE 5000
