FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
RUN apt-get update \
    && apt-get install -y --allow-unauthenticated \
        libc6-dev \
        libgdiplus \
        libx11-dev \
        ffmpeg \
     && rm -rf /var/lib/apt/lists/*
COPY backend/MyNAS.Site/bin/Release/netcoreapp3.1/publish ./
COPY frontend/dist/UI ./wwwroot
ENTRYPOINT ["dotnet", "MyNAS.Site.dll"]
EXPOSE 5000
